const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const escapeHtml = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dollars = v => v == null ? '—' : '$' + Number(v).toLocaleString('zh-TW',{minimumFractionDigits:2,maximumFractionDigits:2});
const signed = v => v == null ? '—' : (Number(v)>=0?'+':'')+Number(v).toFixed(2)+'%';
const time = v => v ? new Date(v).toLocaleString('zh-TW',{hour12:false}) : '—';
const stageName = {PREPARING:'準備中',INFORMATION:'情報閱讀',DISCUSSION:'情報交流',TRADING:'交易進行中',CLOSED:'交易已關閉',RESULT:'績效公布',BREAK:'休息時間',FINISHED:'活動結束'};
const icon = {dashboard:'◫',setup:'⚙',teams:'◉',stocks:'◈',rounds:'◷',intelligence:'✦',snapshots:'▥',import:'⇧',market:'◈',portfolio:'◫',transactions:'↕',ranking:'▥'};
const app = $('#app');
const state = {page: location.pathname.startsWith('/presenter/')?'presenter':location.pathname.startsWith('/team')?'team':'admin',adminTab:'dashboard',teamTab:'market',activities:[],aid:Number(localStorage.getItem('camp_aid')||0),dashboard:null,team:null,presenter:null,stockId:null,link:null,timer:0};

async function api(path, method='GET', body){
  const opts={method,credentials:'same-origin',headers:{}};
  if(body!==undefined){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(body)}
  const res=await fetch(path,opts);
  let data; try{data=await res.json()}catch{data={error:'伺服器回應格式錯誤'}}
  if(!res.ok)throw new Error(data.error||`HTTP ${res.status}`);
  return data;
}
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className=(error?'error ':'')+'show';clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='',4000)}
function fatal(msg){app.innerHTML=`<div class="auth"><div class="card auth-card"><div class="brand"><span class="brandmark">↗</span><span>Camp Invest<small>INVESTMENT CHALLENGE</small></span></div><h1>無法載入</h1><p>${escapeHtml(msg)}</p><button class="btn primary" data-action="reload">重新整理</button></div></div>`}
function badge(text,kind=''){return `<span class="badge ${kind}">${escapeHtml(text)}</span>`}
function empty(title,text=''){return `<div class="empty"><strong>${escapeHtml(title)}</strong>${escapeHtml(text)}</div>`}
function field(label,name,type='text',value='',extra=''){return `<label>${escapeHtml(label)}<input name="${name}" type="${type}" value="${escapeHtml(value)}" ${extra}></label>`}
function btn(label,action,klass='',extra=''){return `<button class="btn ${klass}" data-action="${action}" ${extra}>${label}</button>`}
function formData(form){const o={};new FormData(form).forEach((v,k)=>o[k]=v);return o}
function modal(title,html,actions=''){let d=$('#modal');if(!d){d=document.createElement('dialog');d.id='modal';document.body.append(d)}d.innerHTML=`<div class="modal-inner"><div class="modal-head"><h2>${escapeHtml(title)}</h2><button class="btn small" data-action="close-modal">✕</button></div>${html}<div class="form-actions">${actions}</div></div>`;d.showModal();return d}
function closeModal(){const d=$('#modal');if(d?.open)d.close()}
function confirmAction(title,body,action){modal(title,`<p>${body}</p>`,`${btn('取消','close-modal')} ${btn('確認執行',action,'primary')}`)}
function spinner(){app.innerHTML='<div class="loading">載入中…</div>'}
function options(list,selected, label='name',value='id'){return list.map(x=>`<option value="${escapeHtml(x[value])}" ${String(x[value])===String(selected)?'selected':''}>${escapeHtml(x[label])}</option>`).join('')}
function getRound(){return state.dashboard?.rounds.find(r=>r.round_number===state.dashboard.current_round)}

async function init(){
  try{
    if(state.page==='admin') await loadAdmin();
    else if(state.page==='team') await loadTeam();
    else await loadPresenter();
  }catch(e){fatal(e.message)}
  setInterval(tick,1000);
  setInterval(async()=>{try{if(state.page==='presenter')await loadPresenter(false);if(state.page==='team')await loadTeam(false)}catch{}},8000);
}
function tick(){if(state.timer>0)state.timer--;$$('[data-clock]').forEach(el=>{el.textContent=formatClock(state.timer)})}
function formatClock(seconds){seconds=Math.max(0,seconds||0);return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}

async function loadAdmin(render=true){
  const me=await api('/api/auth/me');
  if(me.role!=='admin'){renderLogin();return}
  state.activities=await api('/api/admin/activities');
  if(!state.activities.some(a=>a.id===state.aid))state.aid=state.activities[0]?.id||0;
  localStorage.setItem('camp_aid',state.aid);
  state.dashboard=state.aid?await api(`/api/admin/activity/${state.aid}`):null;
  state.timer=state.dashboard?.timer_remaining_live||0;
  if(render)renderAdmin();
}
function renderLogin(){app.innerHTML=`<div class="auth"><div class="card auth-card"><div class="brand"><span class="brandmark">↗</span><span>Camp Invest<small>ADMIN CONSOLE</small></span></div><h1>主持人登入</h1><p>請輸入第一次啟動伺服器時顯示的管理員密碼。</p><form data-form="login"><label>管理員密碼<input type="password" name="password" required autocomplete="current-password" autofocus></label><button class="btn primary block">登入後台 →</button></form></div></div>`}
const adminTabs=[['dashboard','總覽'],['setup','活動設定'],['teams','隊伍'],['stocks','股票'],['rounds','回合與價格'],['intelligence','情報'],['transactions','交易紀錄'],['snapshots','績效快照'],['import','匯入']];
function renderAdmin(){
  const a=state.dashboard;
  app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><span class="brandmark">↗</span><span>Camp Invest<small>ADMIN CONSOLE</small></span></div><nav class="nav">${adminTabs.map(([id,label])=>`<button data-tab="${id}" class="${state.adminTab===id?'active':''}"><span>${icon[id]||'↕'}</span>${label}</button>`).join('')}</nav><div class="sidefoot">營隊模擬投資競賽平台<br>資訊不對稱 · 團隊決策</div></aside><main class="main"><div class="topbar"><div><div class="eyebrow">CONTROL ROOM / HOST DASHBOARD</div><h1>${escapeHtml(adminTabs.find(x=>x[0]===state.adminTab)?.[1]||'總覽')}</h1></div><div class="top-actions"><select class="select-activity" id="activity-select">${state.activities.length?options(state.activities,state.aid):'<option value="0">尚無活動</option>'}</select>${btn('＋ 新活動','new-activity','small')}${btn('登出','logout','small ghost')}</div></div>${a?renderAdminTab(a):renderNoActivity()}</main></div>`;
  if(a&&state.adminTab==='transactions')loadAdminTransactions();
}
async function loadAdminTransactions(){try{const tx=await api(`/api/admin/activity/${state.aid}/transactions`);const el=$('#admin-async');if(!el)return;el.outerHTML=tx.length?`<div class="tablewrap"><table><thead><tr><th>時間</th><th>隊伍</th><th>回合</th><th>股票</th><th>方向</th><th>股數</th><th>價格</th><th>金額</th></tr></thead><tbody>${tx.map(t=>`<tr><td>${time(t.created_at)}</td><td>${escapeHtml(t.team_name)}</td><td>R${t.round_number}</td><td>${escapeHtml(t.symbol)}</td><td>${badge(t.type==='BUY'?'買入':'賣出',t.type==='BUY'?'green':'gold')}</td><td>${t.quantity}</td><td>${dollars(t.price)}</td><td>${dollars(t.total_amount)}</td></tr>`).join('')}</tbody></table></div>`:empty('尚無交易紀錄')}catch(e){toast(e.message,true)}}
function renderNoActivity(){return `<div class="hero"><div class="eyebrow">WELCOME</div><h1>建立第一場投資競賽</h1><p>設定共同起始資金，接著新增隊伍、股票、回合價格和情報。</p>${btn('建立活動 →','new-activity','primary')}</div>`}
function renderAdminTab(a){switch(state.adminTab){case 'setup':return renderSetup(a);case 'teams':return renderTeams(a);case 'stocks':return renderStocks(a);case 'rounds':return renderRounds(a);case 'intelligence':return renderIntelAdmin(a);case 'transactions':return '<div id="admin-async" class="loading">載入交易紀錄…</div>';case 'snapshots':return renderSnapshots(a);case 'import':return renderImport(a);default:return renderDashboard(a)}}
function renderDashboard(a){
  const active=a.status==='ACTIVE';
  return `<section class="hero"><div class="hero-num">${a.current_round||'—'}</div><div class="eyebrow">${escapeHtml(a.code)} · ${active?'LIVE ACTIVITY':'FINISHED'}</div><h1>${escapeHtml(a.name)}</h1><p>ROUND ${a.current_round||'—'} &nbsp;·&nbsp; ${stageName[a.stage]||a.stage} &nbsp;·&nbsp; ${a.stage==='TRADING'?'交易開放':'交易關閉'}</p><div class="hero-actions">${btn('開啟投影畫面 ↗','open-presenter','primary')} ${btn('複製活動','duplicate','ghost')}</div></section>
  <section class="section"><div class="grid four"><div class="card metric"><div class="label">CURRENT ROUND</div><div class="value">${a.current_round||'—'}</div><div class="sub">${stageName[a.stage]}</div></div><div class="card metric"><div class="label">TEAMS</div><div class="value">${a.teams.length}</div><div class="sub">已建立隊伍</div></div><div class="card metric"><div class="label">STOCKS</div><div class="value">${a.stocks.length}</div><div class="sub">虛構股票</div></div><div class="card metric"><div class="label">PUBLISHED SNAPSHOT</div><div class="value">${a.published_snapshot?'#'+a.published_snapshot.id:'—'}</div><div class="sub">${a.published_snapshot?time(a.published_snapshot.published_at):'尚未公布'}</div></div></div></section>
  <section class="section"><div class="section-head"><h2>現場快速控制</h2>${badge(a.stage==='TRADING'?'交易開放':'交易關閉',a.stage==='TRADING'?'green':'red')}</div><div class="card pad quick"><div class="btnrow">${btn('① 發布隊伍情報','preview-release','')}${btn('② 開始交流','stage-discussion','')}${btn('③ 開放交易','stage-trading','primary')}${btn('④ 關閉交易','stage-closed','warn')}${btn('⑤ 建立績效快照','quick-snapshot','')}${btn('⑥ 公布績效','go-snapshots','')}${btn('⑦ 下一回合','next-round','')}</div></div></section>
  <section class="grid two section"><div class="card pad"><div class="section-head"><h2>階段計時器</h2>${badge(a.timer_mode==='AUTOMATIC'?'自動關閉':'手動控制','aqua')}</div><div class="value mono" data-clock style="font-size:48px;font-weight:800">${formatClock(state.timer)}</div><div class="form-actions"><input id="timer-minutes" type="number" min="0" value="10" style="width:95px" aria-label="分鐘"><span class="muted tiny" style="align-self:center">分鐘</span>${btn('開始','timer-start','small primary')}${btn('暫停','timer-pause','small')}${btn('繼續','timer-resume','small')}${btn('重設','timer-reset','small')}${btn('跳過','timer-skip','small')}</div></div><div class="card pad"><h2>活動狀態</h2><p>初始資金 ${dollars(a.initial_cash)} · 已完成 ${a.transaction_count} 筆交易</p><p>目前處於 <strong>${stageName[a.stage]}</strong>。切換回合時，系統才會套用下一回合價格。</p>${a.status==='FINISHED'?badge('活動已結束','gold'):btn('查看回合與價格 →','go-rounds','small')}</div></section>`;
}
function renderSetup(a){return `<div class="grid two"><section class="card pad"><h2>活動設定</h2><p class="muted tiny">活動代碼：<strong>${escapeHtml(a.code)}</strong> · 初始資金：${dollars(a.initial_cash)}</p><form data-form="settings" class="formgrid">${field('活動名稱','name','text',a.name,'required')}
  <label>交易倒數結束<select name="timer_mode"><option value="MANUAL" ${a.timer_mode==='MANUAL'?'selected':''}>只通知主持人（建議）</option><option value="AUTOMATIC" ${a.timer_mode==='AUTOMATIC'?'selected':''}>自動關閉交易</option></select></label>
  <label class="check wide"><input type="checkbox" name="performance_report_visible" ${a.performance_report_visible?'checked':''}><span>允許隊伍查看最終績效報告</span></label><label class="check wide"><input type="checkbox" name="review_visible" ${a.review_visible?'checked':''}><span>開放情報復盤（公開已發送情報與接收隊伍）</span></label><div class="wide"> <button class="btn primary">儲存設定</button></div></form></section>
  <section class="card pad"><h2>階段控制</h2><p class="muted tiny">選擇目前回合的展示階段，交易只在「交易進行中」開放。</p><div class="btnrow">${['INFORMATION','DISCUSSION','TRADING','CLOSED','RESULT','BREAK'].map(x=>btn(stageName[x],`setstage-${x}`,a.stage===x?'primary':'' )).join('')}</div><div class="divider"></div><h2>活動連結</h2><p class="tiny">投影畫面為公開唯讀，不含隊伍秘密資訊。</p><div class="linkbox">${escapeHtml(location.origin+'/presenter/'+a.code)}</div></section></div><section class="card pad section"><h2>刪除活動</h2><p class="muted tiny">刪除「${escapeHtml(a.name)}」及其隊伍、股票、情報、交易紀錄與績效快照。此操作無法復原。</p>${btn('刪除這個活動','delete-activity','danger')}</section>`}
function renderTeams(a){return `<div class="grid two"><section class="card pad"><h2>新增隊伍</h2><p class="muted tiny">每隊共用一台裝置。建立後會產生一次性可複製的加入連結。</p><form data-form="team" class="formgrid">${field('隊伍名稱','name','text','','required class="wide"')}<div class="wide"><button class="btn primary">新增隊伍</button></div></form></section><section class="card pad"><h2>加入方式</h2><p>主持人將加入連結或 QR Code 傳給指定隊伍。隊伍開啟後會建立持續登入狀態。</p><div class="notice">重新產生隊伍連結會使舊連結及舊登入失效。</div></section></div><section class="section"><div class="section-head"><h2>隊伍清單</h2>${badge(`${a.teams.length} 隊`,'aqua')}</div>${a.teams.length?`<div class="tablewrap"><table><thead><tr><th>隊伍</th><th>建立時間</th><th>加入連結</th></tr></thead><tbody>${a.teams.map(t=>`<tr><td><strong>${escapeHtml(t.name)}</strong></td><td>${time(t.created_at)}</td><td>${btn('產生新連結 / QR','regen-'+t.id,'small')}</td></tr>`).join('')}</tbody></table></div>`:empty('尚未建立隊伍','先建立隊伍，再分配情報。')}</section>`}
function parseFields(v){return String(v||'').split('\n').map(s=>s.trim()).filter(Boolean).map(s=>{const i=s.indexOf('：')>=0?s.indexOf('：'):s.indexOf(':');return {field_name:i>=0?s.slice(0,i).trim():s,field_value:i>=0?s.slice(i+1).trim():''}})}
function fieldsText(fields){return fields.map(f=>`${f.field_name}：${f.field_value}`).join('\n')}
function renderStocks(a){return `<section class="card pad"><h2>新增股票</h2><p class="muted tiny">股票由主持人定義，交易量不會影響價格。</p><form data-form="stock" class="formgrid">${field('股票代號','symbol','text','','required placeholder="NT01"')}${field('公司名稱','name','text','','required')}${field('產業','industry')}${field('Logo 圖片網址','logo','url')}
  <label class="wide">公司背景與說明<textarea name="description"></textarea></label><label class="wide">財務資料<textarea name="financials"></textarea></label><label class="wide">自訂欄位（每行一筆：名稱：內容）<textarea name="fields" placeholder="市占率：27%&#10;營收成長率：15%"></textarea></label><div class="wide"><button class="btn primary">新增股票</button></div></form></section><section class="section"><div class="section-head"><h2>股票資料</h2>${badge(`${a.stocks.length} 檔`,'aqua')}</div>${a.stocks.length?`<div class="grid three">${a.stocks.map(s=>`<div class="card pad"><div class="stock-heading"><span class="symbol">${escapeHtml(s.symbol.slice(0,2))}</span>${badge(s.industry||'未分類')}</div><h2 style="margin:14px 0 2px">${escapeHtml(s.name)}</h2><div class="muted tiny">${escapeHtml(s.symbol)}</div><div class="stock-price">${dollars(s.price)}</div><div class="muted tiny">${s.history.length} 回合價格資料</div><div class="form-actions">${btn('編輯資料','edit-stock-'+s.id,'small')}</div></div>`).join('')}</div>`:empty('尚未建立股票')}</section>`}
function renderRounds(a){const future=a.rounds.filter(r=>r.round_number>a.current_round);return `<div class="grid two"><section class="card pad"><h2>新增回合</h2><form data-form="round" class="formgrid">${field('回合編號','round_number','number',a.rounds.length+1,'min="1" required')}<div class="wide"><button class="btn primary">新增回合</button></div></form><p class="muted tiny">請依序建立回合，並為每檔股票設定該回合價格。</p></section><section class="card pad"><h2>設定回合股價</h2><form data-form="price" class="formgrid"><label>回合<select name="round_id" required>${options(future,'','round_number')}</select></label><label>股票<select name="stock_id" required>${options(a.stocks,'','symbol')}</select></label>${field('固定價格','price','number','','min="0.01" step="0.01" required')}<div style="align-self:end"><button class="btn primary">儲存價格</button></div></form></section></div><section class="section"><div class="section-head"><h2>回合價格表</h2>${btn('進入下一回合','next-round','primary')}</div>${a.rounds.length?`<div class="tablewrap"><table><thead><tr><th>回合</th><th>狀態</th>${a.stocks.map(s=>`<th>${escapeHtml(s.symbol)}</th>`).join('')}</tr></thead><tbody>${a.rounds.map(r=>`<tr><td>Round ${r.round_number}</td><td>${badge(r.status,r.status==='ACTIVE'?'green':'')}</td>${a.stocks.map(s=>`<td class="mono">${dollars(r.prices.find(p=>p.stock_id===s.id)?.price)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty('尚未建立回合')}</section>`}
function teamChecks(a,selected=[]){return `<div class="btnrow">${a.teams.map(t=>`<label class="check item" style="padding:8px 10px"><input type="checkbox" name="team_ids" value="${t.id}" ${selected.includes(t.id)?'checked':''}>${escapeHtml(t.name)}</label>`).join('')}</div>`}
function renderIntelAdmin(a){return `<section class="card pad"><div class="section-head"><h2>建立情報</h2>${badge('隊伍專屬 · 可公開','aqua')}</div><form data-form="news" class="formgrid"><label>所屬回合<select name="round_id" required>${options(a.rounds,a.rounds.find(r=>r.round_number===a.current_round)?.id||a.rounds[0]?.id,'round_number')}</select></label><label>情報類型<select name="type"><option value="PRIVATE">PRIVATE · 單隊</option><option value="GROUP">GROUP · 多隊</option><option value="PUBLIC">PUBLIC · 全部隊伍</option></select></label>${field('標題','title','text','','required')}${field('分類','category')}
  <label class="wide">內容<textarea name="content" required></textarea></label>${field('圖片網址（選填）','image','url','','class="wide"')}<div class="wide"><label>接收隊伍（PUBLIC 不需選）</label>${teamChecks(a)}</div><div class="wide"><button class="btn primary">建立待發布情報</button></div></form></section>
  <section class="section"><div class="section-head"><h2>情報發送檢查</h2><div class="btnrow">${btn('預覽本回合分配','preview-release','small')}${btn('隨機分配','random-assign','small')}</div></div>${a.news.length?`<div class="tablewrap"><table><thead><tr><th>情報</th><th>回合</th><th>類型</th><th>接收隊伍</th><th>狀態</th><th>操作</th></tr></thead><tbody>${a.news.map(n=>`<tr><td><strong>${escapeHtml(n.title)}</strong></td><td>${n.round_number}</td><td>${badge(n.type,n.type==='PUBLIC'?'gold':'')}</td><td>${escapeHtml(n.assignments.map(x=>x.team_name).join('、')||'—')}</td><td>${badge(n.assignments.some(x=>x.released)?'已發送':'待發布',n.assignments.some(x=>x.released)?'green':'')}</td><td>${!n.assignments.some(x=>x.released)?btn('編輯','edit-news-'+n.id,'small'):''} ${n.type!=='PUBLIC'?btn('公開','public-news-'+n.id,'small'):''}</td></tr>`).join('')}</tbody></table></div>`:empty('尚未建立情報')}</section>`}
function renderSnapshots(a){return `<div class="grid two"><section class="card pad"><h2>建立績效快照</h2><p class="muted tiny">系統會立即保存每隊資產與排名；建立後仍需手動公布。</p><form data-form="snapshot" class="formgrid"><label>顯示層級<select name="display_level"><option value="C">C · 排名、總資產、報酬率</option><option value="B">B · 排名、總資產</option><option value="A">A · 只有排名與隊名</option></select></label><label class="check"><input type="checkbox" name="is_final"><span>最終快照（將結束活動）</span></label><div class="wide"><button class="btn primary">建立快照</button></div></form></section><section class="card pad"><h2>已公開排行</h2>${a.published_snapshot?`<p>快照 #${a.published_snapshot.id} · Round ${a.published_snapshot.round_number}</p><p class="muted tiny">公布於 ${time(a.published_snapshot.published_at)}</p>${a.published_snapshot.entries.slice(0,3).map(e=>`<div class="ranking-row"><span class="rank">${e.rank}</span><strong>${escapeHtml(e.team_name)}</strong><span>${e.total_asset?dollars(e.total_asset):''}</span><span class="rate">${e.return_rate?signed(e.return_rate):''}</span></div>`).join('')}`:empty('尚未公布績效')}</section></div><section class="section"><div class="section-head"><h2>歷史快照</h2>${badge(`${a.snapshots.length} 次`,'aqua')}</div>${a.snapshots.length?`<div class="tablewrap"><table><thead><tr><th>快照</th><th>建立時間</th><th>層級</th><th>狀態</th><th>操作</th></tr></thead><tbody>${a.snapshots.map(s=>`<tr><td><strong>#${s.id}</strong> ${s.is_final?badge('FINAL','gold'):''}</td><td>${time(s.created_at)}</td><td>${s.display_level}</td><td>${badge(s.is_published?'已公布':'隱藏',s.is_published?'green':'red')}</td><td>${btn('查看結果','view-snapshot-'+s.id,'small')} ${s.is_published?'':btn('公布','publish-'+s.id,'small primary')}</td></tr>`).join('')}</tbody></table></div>`:empty('尚未建立快照')}</section>`}
function renderImport(a){return `<div class="grid two"><section class="card pad"><h2>批次匯入股價</h2><p class="muted tiny">第一欄為 Round，其餘欄名為股票代號。支援 CSV 與 XLSX。</p><div class="linkbox mono">Round,NT01,GP01<br>1,100,80<br>2,120,75</div><form data-form="import-prices" class="stack" style="margin-top:15px"><label>選擇 CSV / XLSX 檔<input type="file" name="file" accept=".csv,.xlsx,text/csv" required></label><button class="btn primary">匯入股價</button></form></section><section class="card pad"><h2>批次匯入情報</h2><p class="muted tiny">每列建立一則私人情報；Team 必須與隊名完全相同。</p><div class="linkbox mono">Round,News,Team,Content<br>2,產品突破,第一隊,測試結果優於預期</div><form data-form="import-news" class="stack" style="margin-top:15px"><label>選擇 CSV / XLSX 檔<input type="file" name="file" accept=".csv,.xlsx,text/csv" required></label><button class="btn primary">匯入情報</button></form></section></div><div class="notice gold section">匯入前請核對回合、股票代號和隊名。XLSX 會讀取第一個工作表。</div>`}

async function loadTeam(render=true){
  const previous=state.team;
  try{state.team=await api('/api/team/me')}catch(e){if(e.message==='請先登入'){renderTeamEntry();return}throw e}
  state.timer=state.team.timer_remaining;
  if(location.pathname.startsWith('/team/stock/')){state.stockId=Number(location.pathname.split('/').pop());state.teamTab='stock'}
  else if(location.pathname.startsWith('/team/'))state.teamTab=location.pathname.split('/')[2]||'market';
  const changed=!previous||previous.round!==state.team.round||previous.stage!==state.team.stage||
    previous.snapshot?.id!==state.team.snapshot?.id||previous.review_visible!==state.team.review_visible||
    JSON.stringify(previous.portfolio)!==JSON.stringify(state.team.portfolio)||
    JSON.stringify(previous.stocks.map(x=>x.price))!==JSON.stringify(state.team.stocks.map(x=>x.price));
  if(render||changed)renderTeam();
  else {const m=$('[data-clock]');if(m)m.textContent=formatClock(state.timer);if(state.teamTab==='intelligence')renderTeamIntel()}
}
function renderTeamEntry(){app.innerHTML=`<div class="auth"><div class="card auth-card"><div class="brand"><span class="brandmark">↗</span><span>Camp Invest<small>TEAM ACCESS</small></span></div><h1>隊伍進入</h1><p>請掃描主持人提供的 QR Code，或使用隊伍專屬連結進入。</p><div class="notice">每個隊伍連結僅限該隊使用。請勿轉傳給其他隊伍。</div></div></div>`}
const teamTabs=[['market','市場'],['intelligence','情報'],['portfolio','資產'],['transactions','紀錄'],['ranking','排名']];
function renderTeam(){const a=state.team;app.innerHTML=`<div class="team-shell"><div class="team-header"><div class="brand"><span class="brandmark">↗</span><span>Camp Invest<small>TEAM TERMINAL</small></span></div><div class="team-id">${escapeHtml(a.team.name)}<br><span class="accent">ROUND ${a.round||'—'} · ${stageName[a.stage]}</span></div></div><nav class="team-nav">${teamTabs.map(([id,label])=>`<button data-teamtab="${id}" class="${state.teamTab===id||(state.teamTab==='stock'&&id==='market')?'active':''}">${label}</button>`).join('')}</nav><div id="team-content">${renderTeamTab(a)}</div><nav class="bottom-nav">${teamTabs.map(([id,label])=>`<button data-teamtab="${id}" class="${state.teamTab===id||(state.teamTab==='stock'&&id==='market')?'active':''}"><b>${icon[id]||'✦'}</b>${label}</button>`).join('')}</nav></div>`;if(state.teamTab==='intelligence')renderTeamIntel();if(state.teamTab==='transactions')renderTransactions().then(replaceTeamContent);if(state.teamTab==='performance')renderPerformance().then(replaceTeamContent);if(state.teamTab==='review')renderReview()}
function renderTeamTab(a){switch(state.teamTab){case 'stock':return renderStockDetail(a);case 'intelligence':case 'transactions':case 'performance':case 'review':return '<div class="loading">載入中…</div>';case 'portfolio':return renderPortfolio(a);case 'ranking':return renderRanking(a);default:return renderMarket(a)}}
function renderMarket(a){return `<section class="hero"><div class="hero-num">${a.round||'—'}</div><div class="eyebrow">${escapeHtml(a.name)} · ROUND ${a.round||'—'}</div><h1>${stageName[a.stage]}</h1><p>${a.stage==='TRADING'?'目前可以按本回合固定價格買入或賣出股票。':'閱讀情報、與其他小隊交流，再決定投資策略。'}</p>${a.timer_running?`<div class="clock mono" data-clock style="font-size:36px;font-weight:800;color:var(--gold)">${formatClock(state.timer)}</div>`:''}</section>
  <section class="section"><div class="grid three"><div class="card metric"><div class="label">可用現金</div><div class="value">${dollars(a.portfolio.cash)}</div></div><div class="card metric"><div class="label">持股市值</div><div class="value">${dollars(a.portfolio.stock_value)}</div></div><div class="card metric"><div class="label">目前總資產</div><div class="value">${dollars(a.portfolio.total_asset)}</div></div></div></section><section class="section"><div class="section-head"><h2>市場行情</h2>${badge('本回合價格固定','aqua')}</div>${a.stocks.length?`<div class="stock-grid">${a.stocks.map(s=>`<div class="card stock-card" data-stock="${s.id}"><div class="stock-heading"><div style="display:flex;gap:10px;align-items:center"><span class="symbol">${escapeHtml(s.symbol.slice(0,2))}</span><div><div class="stock-name">${escapeHtml(s.name)}</div><div class="muted tiny">${escapeHtml(s.symbol)} · ${escapeHtml(s.industry)}</div></div></div><span class="muted">↗</span></div><div class="stock-price">${dollars(s.price)}</div><div class="${Number(s.change_percent)>=0?'gain':'loss'} tiny">${s.change_percent==null?'首回合':signed(s.change_percent)+' 較上回合'}</div></div>`).join('')}</div>`:empty('尚無股票')}</section>`}
function chart(s){const data=s.history.map(x=>Number(x.price));if(!data.length)return empty('尚無價格歷史');const min=Math.min(...data),max=Math.max(...data),span=max-min||1,step=data.length>1?100/(data.length-1):0;const pts=data.map((x,i)=>`${i*step},${90-((x-min)/span)*70}`).join(' ');return `<svg class="chart" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="歷史股價折線圖"><defs><linearGradient id="grad"><stop stop-color="#4de3cb" stop-opacity=".22"/><stop offset="1" stop-color="#4de3cb" stop-opacity="0"/></linearGradient></defs><polygon points="0,100 ${pts} 100,100" fill="url(#grad)"/><polyline points="${pts}" fill="none" stroke="#4de3cb" stroke-width="2" vector-effect="non-scaling-stroke"/>${data.map((x,i)=>`<circle cx="${i*step}" cy="${90-((x-min)/span)*70}" r="1.6" fill="#4de3cb"/>`).join('')}</svg><div class="muted tiny">${s.history.map(x=>`R${x.round}: ${dollars(x.price)}`).join(' · ')}</div>`}
function renderStockDetail(a){const s=a.stocks.find(x=>x.id===state.stockId);if(!s)return empty('找不到股票');const holding=a.portfolio.holdings.find(x=>x.stock_id===s.id);return `${btn('← 返回市場','back-market','small ghost')}<div class="section stock-detail"><div class="stack"><div class="card pad"><div class="eyebrow">${escapeHtml(s.symbol)} · ${escapeHtml(s.industry)}</div>${s.logo?`<img src="${escapeHtml(s.logo)}" alt="${escapeHtml(s.name)} logo" style="max-width:90px;max-height:90px;object-fit:contain;float:right">`:''}<h1 class="page-title">${escapeHtml(s.name)}</h1><div class="stock-price" style="font-size:42px">${dollars(s.price)}</div><div class="${Number(s.change_percent)>=0?'gain':'loss'}">${s.change_percent==null?'首回合':signed(s.change_percent)+' 較上回合'}</div><div class="divider"></div><h2>歷史價格</h2>${chart(s)}</div><div class="card pad"><h2>公司資料</h2><p class="muted" style="white-space:pre-line;line-height:1.8">${escapeHtml(s.description||'主持人尚未提供說明。')}</p>${s.financials?`<div class="divider"></div><h3>財務資料</h3><p class="muted" style="white-space:pre-line">${escapeHtml(s.financials)}</p>`:''}${s.fields.length?`<div class="divider"></div><div class="info-grid">${s.fields.map(f=>`<div class="info-cell"><span>${escapeHtml(f.field_name)}</span><strong>${escapeHtml(f.field_value)}</strong></div>`).join('')}</div>`:''}</div></div><div class="stack"><div class="card pad"><h2>我的持股</h2><div class="info-grid"><div class="info-cell"><span>股數</span><strong>${holding?.quantity||0}</strong></div><div class="info-cell"><span>平均成本</span><strong>${dollars(holding?.average_cost||0)}</strong></div><div class="info-cell"><span>市值</span><strong>${dollars(holding?.market_value||0)}</strong></div><div class="info-cell"><span>未實現損益</span><strong class="${Number(holding?.unrealized_profit||0)>=0?'gain':'loss'}">${dollars(holding?.unrealized_profit||0)}</strong></div></div></div><div class="card pad"><h2>本回合交易</h2>${a.stage==='TRADING'?`<p class="muted tiny">成交價格固定為 ${dollars(s.price)}；最小單位 1 股。</p><form data-form="trade" class="stack"><input type="hidden" name="stock_id" value="${s.id}"><label>方向<select name="type"><option value="BUY">買入</option><option value="SELL">賣出</option></select></label>${field('股數','quantity','number',1,'min="1" step="1" required')}<button class="btn primary block">確認交易</button></form>`:`<div class="notice gold">目前交易關閉。主持人開放交易後即可下單。</div>`}</div></div></div>`}
async function renderTeamIntel(){const news=await api('/api/team/intelligence');if(state.teamTab!=='intelligence')return;const groups=[...new Set(news.map(n=>n.round_number))].sort((a,b)=>b-a);const html=`<div class="eyebrow">YOUR INTELLIGENCE</div><h1 class="page-title">小隊情報</h1><div class="notice">這裡只顯示你的小隊已取得的情報與公開消息。你可以自行與其他隊伍交流。</div>${state.team.review_visible?`<div class="form-actions">${btn('查看情報復盤 →','open-review','small')}</div>`:''}${groups.length?groups.map(round=>`<section class="section"><div class="section-head"><h2>Round ${round}</h2>${badge(news.filter(n=>n.round_number===round).length+' 則')}</div><div class="stack">${news.filter(n=>n.round_number===round).map(n=>`<div class="card intel-card ${n.type==='PUBLIC'?'public':''}"><div class="eyebrow">${escapeHtml(n.category||'MARKET SIGNAL')}</div><h3>${escapeHtml(n.title)}</h3><p>${escapeHtml(n.content)}</p>${n.image?`<img src="${escapeHtml(n.image)}" alt="${escapeHtml(n.title)}" style="max-width:100%;border-radius:10px">`:''}<div class="muted tiny">${n.type==='PUBLIC'?'公開情報':'此情報僅提供給你的小隊'} · ${time(n.released_at)}</div></div>`).join('')}</div></section>`).join(''):empty('尚未收到情報','請等待主持人發布本回合情報。')}`;replaceTeamContent(html)}
async function renderReview(){try{const items=await api('/api/team/review');if(state.teamTab!=='review')return;const rounds=[...new Set(items.map(x=>x.round_number))].sort((a,b)=>a-b);replaceTeamContent(`<div class="eyebrow">INFORMATION REVIEW</div><h1 class="page-title">情報復盤</h1><div class="notice">主持人已開放復盤。下列為各隊實際收到的情報，供活動討論。</div>${rounds.map(r=>`<section class="section"><h2>Round ${r}</h2><div class="grid two">${items.filter(x=>x.round_number===r).map(x=>`<div class="card pad"><div class="eyebrow">${escapeHtml(x.team_name)}</div><h3>${escapeHtml(x.title)}</h3><p class="muted" style="white-space:pre-line">${escapeHtml(x.content)}</p></div>`).join('')}</div></section>`).join('')}`)}catch(e){toast(e.message,true);state.teamTab='intelligence';renderTeam()}}
function renderPortfolio(a){return `<div class="eyebrow">LIVE PORTFOLIO</div><h1 class="page-title">我的資產</h1><div class="grid three section"><div class="card metric"><div class="label">現金</div><div class="value">${dollars(a.portfolio.cash)}</div></div><div class="card metric"><div class="label">持股市值</div><div class="value">${dollars(a.portfolio.stock_value)}</div></div><div class="card metric"><div class="label">目前總資產</div><div class="value">${dollars(a.portfolio.total_asset)}</div></div></div><section class="section"><div class="section-head"><h2>持股明細</h2>${badge(`${a.portfolio.holdings.length} 檔`,'aqua')}</div>${a.portfolio.holdings.length?`<div class="tablewrap"><table><thead><tr><th>股票</th><th>股數</th><th>均價</th><th>現價</th><th>市值</th><th>未實現損益</th></tr></thead><tbody>${a.portfolio.holdings.map(h=>`<tr><td><strong>${escapeHtml(h.symbol)}</strong> ${escapeHtml(h.name)}</td><td>${h.quantity}</td><td>${dollars(h.average_cost)}</td><td>${dollars(h.price)}</td><td>${dollars(h.market_value)}</td><td class="${Number(h.unrealized_profit)>=0?'gain':'loss'}">${dollars(h.unrealized_profit)}</td></tr>`).join('')}</tbody></table></div>`:empty('尚無持股','前往市場挑選股票。')}</section>`}
async function renderTransactions(){const tx=await api('/api/team/transactions');return `<div class="eyebrow">TRADE HISTORY</div><h1 class="page-title">交易紀錄</h1>${tx.length?`<div class="tablewrap section"><table><thead><tr><th>時間</th><th>回合</th><th>股票</th><th>方向</th><th>股數</th><th>價格</th><th>金額</th></tr></thead><tbody>${tx.map(t=>`<tr><td>${time(t.created_at)}</td><td>R${t.round_number}</td><td>${escapeHtml(t.symbol)}</td><td>${badge(t.type==='BUY'?'買入':'賣出',t.type==='BUY'?'green':'gold')}</td><td>${t.quantity}</td><td>${dollars(t.price)}</td><td>${dollars(t.total_amount)}</td></tr>`).join('')}</tbody></table></div>`:empty('尚無交易紀錄')}`}
function renderRanking(a){const s=a.snapshot;return `<div class="eyebrow">PUBLISHED PERFORMANCE</div><h1 class="page-title">績效排行</h1><div class="notice gold">這是主持人最近一次公布的績效快照，可能不是目前的即時資產。</div>${s?`<div class="section-head section"><h2>績效公布 #${s.id}</h2>${badge(`Round ${s.round_number} · ${time(s.published_at)}`,'aqua')}</div><div class="card">${s.entries.map(e=>`<div class="ranking-row"><span class="rank">${e.rank}</span><strong>${escapeHtml(e.team_name)}</strong><span class="mono">${e.total_asset?dollars(e.total_asset):''}</span><span class="rate ${Number(e.return_rate)>=0?'gain':'loss'}">${e.return_rate?signed(e.return_rate):''}</span></div>`).join('')}</div>${s.is_final?`<div class="form-actions">${btn('查看我的最終報告','show-performance','primary')}</div>`:''}`:empty('目前尚未公布績效','主持人公布後，這裡才會出現排行榜。')}`}
async function renderPerformance(){try{const r=await api('/api/team/performance');return `<div class="eyebrow">FINAL REPORT</div><h1 class="page-title">我的最終報告</h1><div class="grid three section"><div class="card metric"><div class="label">最終名次</div><div class="value">#${r.rank}</div></div><div class="card metric"><div class="label">最終資產</div><div class="value">${dollars(r.total_asset)}</div></div><div class="card metric"><div class="label">報酬率</div><div class="value ${Number(r.return_rate)>=0?'gain':'loss'}">${signed(r.return_rate)}</div></div></div><div class="card pad"><h2>績效摘要</h2><p>初始資金 ${dollars(r.report.initial_cash)} · 交易 ${r.report.transaction_count} 次</p><p>最大獲利股票：${escapeHtml(r.report.best_stock||'—')} · 最大虧損股票：${escapeHtml(r.report.worst_stock||'—')}</p></div><div class="section"><h2>各股票損益</h2>${r.report.stock_results?.length?`<div class="tablewrap"><table><thead><tr><th>股票</th><th>已實現</th><th>未實現</th><th>合計</th></tr></thead><tbody>${r.report.stock_results.map(x=>`<tr><td>${escapeHtml(x.symbol)}</td><td>${dollars(x.realized)}</td><td>${dollars(x.unrealized)}</td><td class="${Number(x.total_profit)>=0?'gain':'loss'}">${dollars(x.total_profit)}</td></tr>`).join('')}</tbody></table></div>`:empty('無股票損益')}</div><div class="section"><h2>最終持股</h2>${r.report.holdings.length?r.report.holdings.map(h=>`<div class="item">${escapeHtml(h.symbol)} · ${h.quantity} 股 · 市值 ${dollars(h.market_value)} · 損益 ${dollars(h.unrealized_profit)}</div>`).join(''):empty('最終沒有持股')}</div><div class="section"><h2>所有交易</h2>${r.report.transactions.length?r.report.transactions.map(t=>`<div class="item">R${t.round_number} · ${escapeHtml(t.symbol)} · ${t.type==='BUY'?'買入':'賣出'} ${t.quantity} 股 · ${dollars(t.total_amount)}</div>`).join(''):empty('沒有交易')}</div>`}catch(e){toast(e.message,true);state.teamTab='ranking';return renderRanking(state.team)}}

async function loadPresenter(render=true){const code=decodeURIComponent(location.pathname.split('/')[2]||'');if(!code){fatal('缺少活動代碼');return}const previous=state.presenter;state.presenter=await api('/api/public/'+encodeURIComponent(code));state.timer=state.presenter.timer_remaining;if(render||!previous||previous.round!==state.presenter.round||previous.stage!==state.presenter.stage||previous.snapshot?.id!==state.presenter.snapshot?.id||JSON.stringify(previous.news)!==JSON.stringify(state.presenter.news)||JSON.stringify(previous.stocks.map(x=>x.price))!==JSON.stringify(state.presenter.stocks.map(x=>x.price)))renderPresenter()}
function renderPresenter(){const a=state.presenter,s=a.snapshot;app.innerHTML=`<div class="presenter"><div class="presenter-head"><div class="brand"><span class="brandmark">↗</span><span>Camp Invest<small>INVESTMENT CHALLENGE</small></span></div><div class="eyebrow">${escapeHtml(a.code)} · LIVE SCREEN</div></div><h1>ROUND ${a.round||'—'}</h1><div class="stage"><span class="statusdot"></span> ${stageName[a.stage]}</div><div class="clock mono" data-clock>${formatClock(state.timer)}</div><div class="presenter-body"><div class="card"><h2>MARKET / 公開市場資訊</h2><div class="presenter-table">${a.stocks.length?a.stocks.map(x=>`<div class="presenter-row"><span>${escapeHtml(x.name)} <span class="muted tiny">${escapeHtml(x.symbol)}</span></span><span>${dollars(x.price)} <small class="${Number(x.change_percent)>=0?'gain':'loss'}">${x.change_percent==null?'':signed(x.change_percent)}</small></span></div>`).join(''):empty('市場資料準備中')}</div></div><div class="card"><h2>${a.stage==='RESULT'||a.stage==='FINISHED'?'RESULT / 已公布績效':'PUBLIC NEWS / 公開情報'}</h2>${(a.stage==='RESULT'||a.stage==='FINISHED')&&s?`<div class="presenter-table">${s.entries.slice(0,5).map(e=>`<div class="presenter-row result"><span><span class="rank">${e.rank}</span>${escapeHtml(e.team_name)}</span><span>${e.total_asset?dollars(e.total_asset):''}</span></div>`).join('')}</div>`:a.news.length?a.news.slice(0,4).map(n=>`<div class="item"><h3>${escapeHtml(n.title)}</h3><p>${escapeHtml(n.content)}</p></div>`).join(''):empty('目前沒有公開情報')}</div></div><div class="presenter-foot">${escapeHtml(a.name)} · ${a.stage==='TRADING'?'交易進行中':'請依主持人指示進行活動'}</div></div>`}

document.addEventListener('click',async e=>{
  const tab=e.target.closest('[data-tab]');if(tab){state.adminTab=tab.dataset.tab;renderAdmin();return}
  const ttab=e.target.closest('[data-teamtab]');if(ttab){state.teamTab=ttab.dataset.teamtab;history.pushState(null,'','/team/'+state.teamTab);renderTeam();return}
  const stock=e.target.closest('[data-stock]');if(stock){state.stockId=Number(stock.dataset.stock);state.teamTab='stock';history.pushState(null,'','/team/stock/'+state.stockId);renderTeam();return}
  const b=e.target.closest('[data-action]');if(!b)return;
  const action=b.dataset.action;
  try{await runAction(action)}catch(err){toast(err.message,true)}
});
function replaceTeamContent(html){const el=$('#team-content');if(el)el.innerHTML=html}
document.addEventListener('change',async e=>{if(e.target.id==='activity-select'){state.aid=Number(e.target.value);localStorage.setItem('camp_aid',state.aid);await loadAdmin()}});
document.addEventListener('submit',async e=>{
  const form=e.target.closest('form[data-form]');if(!form)return;e.preventDefault();const kind=form.dataset.form;const d=formData(form);
  try{await submitForm(kind,d,form)}catch(err){toast(err.message,true)}
});
window.addEventListener('popstate',()=>{if(state.page==='team'){state.teamTab=location.pathname.split('/')[2]||'market';if(state.teamTab==='stock')state.stockId=Number(location.pathname.split('/')[3]);renderTeam()}});

async function submitForm(kind,d,form){const aid=state.aid;
  if(kind==='login'){await api('/api/auth/login','POST',{password:d.password});toast('登入成功');await loadAdmin();return}
  if(kind==='activity'){const r=await api('/api/admin/activities','POST',{name:d.name,code:d.code,initial_cash:d.initial_cash});state.aid=r.id;state.adminTab='dashboard';closeModal();toast('活動已建立');await loadAdmin();return}
  if(kind==='team'){const r=await api(`/api/admin/activity/${aid}/teams`,'POST',{name:d.name});toast('隊伍已建立');await loadAdmin();showTeamLink(r);return}
  if(kind==='stock'){await api(`/api/admin/activity/${aid}/stocks`,'POST',{...d,fields:parseFields(d.fields)});toast('股票已新增');await loadAdmin();return}
  if(kind==='edit-stock'){await api(`/api/admin/activity/${aid}/stocks/${d.id}`,'POST',{...d,fields:parseFields(d.fields)});closeModal();toast('股票資料已更新');await loadAdmin();return}
  if(kind==='round'){await api(`/api/admin/activity/${aid}/rounds`,'POST',{round_number:d.round_number});toast('回合已建立');await loadAdmin();return}
  if(kind==='price'){await api(`/api/admin/activity/${aid}/prices`,'POST',d);toast('股價已儲存');await loadAdmin();return}
  if(kind==='news'||kind==='edit-news'){
    const team_ids=$$('input[name=team_ids]:checked',form).map(x=>Number(x.value));
    const payload={...d,team_ids};if(payload.type==='PUBLIC')payload.team_ids=[];
    if(kind==='news'){await api(`/api/admin/activity/${aid}/news`,'POST',payload);toast('情報已建立')}
    else {await api(`/api/admin/activity/${aid}/news/${d.id}`,'POST',payload);closeModal();toast('情報已更新')}
    await loadAdmin();return;
  }
  if(kind==='snapshot'){const is_final=!!form.querySelector('[name=is_final]').checked;if(is_final){confirmAction('建立最終快照',`<strong>這會立即結束活動並鎖定最終成績。</strong> 建立後仍需手動公布。`,'confirm-final-snapshot');state.pendingSnapshot={display_level:d.display_level,is_final:true};return}await api(`/api/admin/activity/${aid}/snapshots`,'POST',{display_level:d.display_level,is_final:false});toast('快照已建立，尚未公布');await loadAdmin();return}
  if(kind==='settings'){await api(`/api/admin/activity/${aid}/settings`,'POST',{name:d.name,timer_mode:d.timer_mode,performance_report_visible:!!form.querySelector('[name=performance_report_visible]').checked,review_visible:!!form.querySelector('[name=review_visible]').checked});toast('設定已儲存');await loadAdmin();return}
  if(kind==='delete-activity'){if(d.code!==state.dashboard.code)throw Error('活動代碼不符');await api(`/api/admin/activity/${aid}/delete`,'POST',{code:d.code});closeModal();state.aid=0;state.adminTab='dashboard';toast('活動已刪除');await loadAdmin();return}
  if(kind==='trade'){const r=await api('/api/team/trade','POST',d);toast(`${d.type==='BUY'?'買入':'賣出'} ${r.quantity} 股 ${r.symbol} · ${dollars(r.total)}`);await loadTeam();return}
  if(kind.startsWith('import-')){const file=form.querySelector('input[type=file]').files[0];if(!file)throw Error('請選擇檔案');const payload={kind:kind.slice(7)};if(file.name.toLowerCase().endsWith('.xlsx')){const binary=new Uint8Array(await file.arrayBuffer());let s='';for(const b of binary)s+=String.fromCharCode(b);payload.xlsx_base64=btoa(s)}else payload.csv=await file.text();const r=await api(`/api/admin/activity/${aid}/import`,'POST',payload);toast(`已匯入 ${r.imported} 筆資料`);await loadAdmin();return}
}

async function runAction(action){const aid=state.aid,a=state.dashboard;
  if(action==='reload'){location.reload();return}
  if(action==='close-modal'){closeModal();return}
  if(action==='logout'){await api('/api/auth/logout','POST',{});renderLogin();return}
  if(action==='new-activity'){modal('建立活動',`<form data-form="activity" class="stack">${field('活動名稱','name','text','','required placeholder="2026 夏季投資營"')}${field('活動代碼（英數字）','code','text','','required placeholder="CAMP2026"')}${field('每隊初始資金','initial_cash','number','1000000','min="1" step="0.01" required')}<button class="btn primary">建立活動</button></form>`);return}
  if(action==='delete-activity'){modal('確認刪除活動',`<form data-form="delete-activity" class="stack"><div class="notice red">這會永久刪除「${escapeHtml(a.name)}」的所有隊伍、持股、交易、情報、回合與績效快照。</div><label>請輸入活動代碼 <strong>${escapeHtml(a.code)}</strong> 確認<input name="code" type="text" autocomplete="off" required></label><button class="btn danger">永久刪除活動</button></form>`);return}
  if(action==='open-presenter'){window.open('/presenter/'+encodeURIComponent(a.code),'_blank','noopener');return}
  if(action==='duplicate'){confirmAction('複製活動',`將複製股票、回合、股價、隊伍名稱及情報設定。新活動從第一回合開始。`,'confirm-duplicate');return}
  if(action==='confirm-duplicate'){const r=await api(`/api/admin/activity/${aid}/duplicate`,'POST',{});state.aid=r.id;closeModal();toast('活動已複製');await loadAdmin();return}
  if(action==='go-rounds'){state.adminTab='rounds';renderAdmin();return}
  if(action==='go-snapshots'){state.adminTab='snapshots';renderAdmin();return}
  if(action==='back-market'){state.teamTab='market';history.pushState(null,'','/team/market');renderTeam();return}
  if(action==='show-performance'){state.teamTab='performance';history.pushState(null,'','/team/performance');replaceTeamContent(await renderPerformance());return}
  if(action==='open-review'){state.teamTab='review';history.pushState(null,'','/team/review');renderTeam();return}
  if(action.startsWith('regen-')){const id=Number(action.slice(6));confirmAction('重新產生隊伍連結',`舊連結和該隊現有登入狀態會立即失效。`,'confirm-regen-'+id);return}
  if(action.startsWith('confirm-regen-')){const id=Number(action.slice(14));const r=await api(`/api/admin/activity/${aid}/teams/${id}/token`,'POST',{});closeModal();showTeamLink(r);return}
  if(action.startsWith('edit-stock-')){const s=a.stocks.find(x=>x.id===Number(action.slice(11)));modal('編輯股票資料',`<form data-form="edit-stock" class="formgrid"><input type="hidden" name="id" value="${s.id}">${field('公司名稱','name','text',s.name,'required')}${field('產業','industry','text',s.industry)}${field('Logo 圖片網址','logo','url',s.logo,'class="wide"')}<label class="wide">公司說明<textarea name="description">${escapeHtml(s.description)}</textarea></label><label class="wide">財務資料<textarea name="financials">${escapeHtml(s.financials)}</textarea></label><label class="wide">自訂欄位<textarea name="fields">${escapeHtml(fieldsText(s.fields))}</textarea></label><div class="wide"><button class="btn primary">儲存</button></div></form>`);return}
  if(action.startsWith('edit-news-')){const n=a.news.find(x=>x.id===Number(action.slice(10)));const released=n.assignments.some(x=>x.released);modal('編輯情報',`<form data-form="edit-news" class="formgrid"><input type="hidden" name="id" value="${n.id}">${field('標題','title','text',n.title,'required')}${field('分類','category','text',n.category)}<label>類型<select name="type">${['PRIVATE','GROUP','PUBLIC'].map(x=>`<option ${n.type===x?'selected':''}>${x}</option>`).join('')}</select></label>${field('圖片網址','image','url',n.image)}<label class="wide">內容<textarea name="content" required>${escapeHtml(n.content)}</textarea></label>${released?`<div class="notice gold wide">已發送情報的接收隊伍不能變更。若需修正，請另建一則更正情報。</div>`:`<div class="wide"><label>接收隊伍</label>${teamChecks(a,n.assignments.map(x=>x.team_id))}</div>`}<div class="wide"><button class="btn primary">儲存</button></div></form>`);if(released)$('form[data-form=edit-news]').dataset.released='1';return}
  if(action.startsWith('public-news-')){const id=Number(action.slice(12));confirmAction('公開情報',`公開後所有隊伍與投影畫面都能看到此情報。`,'confirm-public-'+id);return}
  if(action.startsWith('confirm-public-')){const id=Number(action.slice(15));await api(`/api/admin/activity/${aid}/news/${id}`,'POST',{type:'PUBLIC'});closeModal();toast('情報已公開');await loadAdmin();return}
  if(action==='preview-release'){const preview=await api(`/api/admin/activity/${aid}/release-preview`);modal(`Round ${a.current_round} 情報發布預覽`,`<div class="modal-list">${preview.map(x=>`<div class="item"><strong>${escapeHtml(x.team_name)}</strong><p>${x.news.length?x.news.map(n=>escapeHtml(n.title)).join('、'):'本次沒有待發布情報'}</p></div>`).join('')}</div><div class="notice gold">請確認每隊收到的情報無誤。已發布情報不可直接換隊。</div>`,`${btn('取消','close-modal')} ${btn('確認發布','confirm-release','primary')}`);return}
  if(action==='confirm-release'){await api(`/api/admin/activity/${aid}/release`,'POST',{});closeModal();toast('隊伍情報已發布');await loadAdmin();return}
  if(action==='random-assign'){const roundId=getRound()?.id;if(!roundId)throw Error('請先開始回合');modal('隨機分配情報',`<p>將目前回合未發布的私人與群組情報建立為新聞池，為每隊抽取指定數量。既有未發布分配會被覆蓋。</p><label>每隊取得則數<input id="random-count" type="number" min="1" value="1"></label>`,`${btn('取消','close-modal')} ${btn('開始分配','confirm-random','primary')}`);return}
  if(action==='confirm-random'){const count=Number($('#random-count').value);await api(`/api/admin/activity/${aid}/random-assign`,'POST',{round_id:getRound().id,count});closeModal();toast('已重新分配，請預覽再發布');await loadAdmin();return}
  if(action==='next-round'){confirmAction('進入下一回合',`系統將鎖定上一回合，套用 Round ${a.current_round+1} 的價格。請先確認下一回合所有股票價格已設定。`,'confirm-next');return}
  if(action==='confirm-next'){const r=await api(`/api/admin/activity/${aid}/next`,'POST',{});closeModal();toast(`已進入 Round ${r.round}`);await loadAdmin();return}
  if(action.startsWith('stage-')||action.startsWith('setstage-')){const stage=action.split('-').at(-1).toUpperCase();if(stage==='TRADING'||stage==='CLOSED'){confirmAction(stage==='TRADING'?'開放交易':'關閉交易',stage==='TRADING'?'隊伍將可以立即按照本回合固定價格下單。':'隊伍將立即無法下單。','confirm-stage-'+stage);return}await api(`/api/admin/activity/${aid}/stage`,'POST',{stage});toast('階段已更新');await loadAdmin();return}
  if(action.startsWith('confirm-stage-')){await api(`/api/admin/activity/${aid}/stage`,'POST',{stage:action.slice(14)});closeModal();toast('交易階段已更新');await loadAdmin();return}
  if(action==='quick-snapshot'){state.adminTab='snapshots';renderAdmin();return}
  if(action==='confirm-final-snapshot'){await api(`/api/admin/activity/${aid}/snapshots`,'POST',state.pendingSnapshot);closeModal();toast('最終成績已鎖定，尚未公布');await loadAdmin();return}
  if(action.startsWith('publish-')){const id=Number(action.slice(8));confirmAction('公布績效快照',`公布快照 #${id} 後，隊伍與投影畫面將看到此份排名。`,'confirm-publish-'+id);return}
  if(action.startsWith('view-snapshot-')){const id=Number(action.slice(14));const detail=await api(`/api/admin/activity/${aid}/snapshots/${id}`);modal(`快照 #${id} 詳細結果`,`<div class="tablewrap"><table><thead><tr><th>名次</th><th>隊伍</th><th>現金</th><th>股票市值</th><th>總資產</th><th>報酬率</th></tr></thead><tbody>${detail.entries.map(x=>`<tr><td>${x.rank}</td><td>${escapeHtml(x.team_name)}</td><td>${dollars(x.cash)}</td><td>${dollars(x.stock_value)}</td><td>${dollars(x.total_asset)}</td><td>${signed(x.return_rate)}</td></tr>`).join('')}</tbody></table></div>`);return}
  if(action.startsWith('confirm-publish-')){const id=Number(action.slice(16));await api(`/api/admin/activity/${aid}/snapshots/${id}/publish`,'POST',{});closeModal();toast('績效已公布');await loadAdmin();return}
  if(action.startsWith('timer-')){const op=action.slice(6);const minutes=Number($('#timer-minutes')?.value||0);await api(`/api/admin/activity/${aid}/timer`,'POST',{action:op,seconds:Math.round(minutes*60)});await loadAdmin();return}
}
function showTeamLink(r){const url=location.origin+r.join_url;modal('隊伍專屬加入連結',`<p>請將此連結或 QR Code 提供給指定隊伍。連結只會在這次產生時顯示。</p><div class="linkbox" id="team-link">${escapeHtml(url)}</div><div id="qr-target" style="text-align:center;margin-top:16px"></div>`,`${btn('複製連結','copy-team-link','primary')}`);state.link=url;renderQr(url)}

async function renderQr(url){const target=$('#qr-target');if(!target)return;target.innerHTML='<p class="muted tiny">QR Code 產生中…</p>';try{const svg=await api('/api/qr?text='+encodeURIComponent(url));target.innerHTML=svg.svg}catch{target.innerHTML='<p class="muted tiny">請複製連結分享給隊伍。</p>'}}
document.addEventListener('click',async e=>{if(e.target.closest('[data-action=copy-team-link]')){await navigator.clipboard.writeText(state.link);toast('連結已複製')}});
init();
